name: aboutme

services:
  pgvector:
    image: ankane/pgvector
    container_name: aboutme-pgvector
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-pgvector}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/volume/data:/var/lib/postgresql/data
    restart: unless-stopped
