spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: gemma:2b-instruct
      embedding:
        model: nomic-embed-text
    embedding:
      options:
        model: text-embedding-ada-002

  vectorstore:
    pgvector:
      uri: ${PGVECTOR_URI:jdbc:postgresql://localhost:5432/pgvector}
      username: ${PGVECTOR_USERNAME:root}
      password: ${PGVECTOR_PASSWORD:1234}
      table-name: ${PGVECTOR_TABLE_NAME:documents}
