server:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000, http://localhost:5173}

# swagger에서 자동으로 error response를 생성하지 않도록 설정
springdoc:
  override-with-generic-response: false
